[monitor]
main = "eDP-1"

[mpd]
using = "false"

[bspwm]
border_width = "3"
top_padding = "50"
bottom_padding = "15"
left_padding = "15"
right_padding = "15"
window_gap = "15"

[polybar]
network_device = "wlo1"

[browser]
cmd = "prime-run google-chrome-stable"
